#!/bin/bash

echo "Без использования js"
let delay=1
let count=0
let itogo=20
echo "-----------"
echo "Переходим к Gulp"
echo "npm init"
sleep 2
npm init 

echo "Installing Gulp"
sleep 2
npm install gulpjs/gulp#4.0


echo "Установка gulp модулей"
echo "-----------"
echo "$((++count)) из $itogo"
echo "gulp-sass"
sleep 2
npm i -D gulp-sass
echo "-----------"
echo "$((++count)) из $itogo"
echo "del"
sleep 2
npm i -D del
echo "-----------"
echo "$((++count)) из $itogo"
echo "gulp-debug"
sleep $delay
npm i -D gulp-debug
echo "$((++count)) из $itogo"
echo "gulp-sourcemaps"
sleep 2
npm i -D gulp-sourcemaps
echo "$((++count)) из $itogo"
echo "gulp-if"
sleep 2
npm i -D gulp-if
echo "$((++count)) из $itogo"
echo "gulp-newer"
sleep 2
npm i -D gulp-newer
echo "$((++count)) из $itogo"
echo "gulp-autoprefixer"
sleep 2
npm i -D gulp-autoprefixer
echo "$((++count)) из $itogo"
echo "gulp-notify"
sleep 2
npm i -D gulp-notify
echo "$((++count)) из $itogo"
echo "browser-sync"
sleep 2
npm i -D browser-sync
echo "$((++count)) из $itogo"
echo "gulp-cssnano"
sleep 2
npm i -D gulp-cssnano
echo "$((++count)) из $itogo"
echo "gulp-rev"
sleep 2
npm i -D gulp-rev
echo "$((++count)) из $itogo"
echo "gulp-rev-replace"
sleep 2
npm i -D gulp-rev-replace
echo "$((++count)) из $itogo"
echo "gulp-imagemin"
sleep 2
npm i -D gulp-imagemin
echo "$((++count)) из $itogo"
echo "imagemin-pngquant"
sleep 2
npm i -D imagemin-pngquant
echo "$((++count)) из $itogo"
echo "gulp-rigger"
sleep 2
npm i -D gulp-rigger
echo "$((++count)) из $itogo"
echo "gulp-minify"
sleep 2
npm i -D gulp-minify
echo "$((++count)) из $itogo"
echo "gulp-uglify"
sleep 2
npm i -D gulp-uglify
echo "$((++count)) из $itogo"
echo "gulp-rename"
sleep 2
npm i -D gulp-rename
echo "-----------"
echo "$((++count)) из $itogo"
echo "gulp-notify"
sleep 2
npm i -D gulp-notify
echo "-----------"
echo "$((++count)) из $itogo"
echo "stream-combiner2"
sleep 2
npm i -D stream-combiner2

echo "-----------"
echo "Все gulp модули загружены"
echo "-----------"

