#!/bin/bash

echo "Без использования js"
let delay=1
let count=0
let itogo=5
let countBower=0
let itogoBower=1
echo "Структура"
sleep $delay
mkdir tmp
mkdir manifest
mkdir src
mkdir src/scss
mkdir src/img
mkdir src/template
mkdir src/fonts

cd src/
touch index.html
cd scss/
touch main.scss
cd ../..


echo "-----------"
echo "Сначала bower"
echo "bower init"
sleep $delay
bower init

echo "-----------"
echo "Переходим к Gulp"
echo "npm init"
sleep $delay
npm init 

echo "Installing Gulp"
sleep $delay
npm install gulpjs/gulp#4.0


echo "Установка gulp модулей"
echo "-----------"
echo "$((++count)) из $itogo"
echo "gulp-load-plugins"
sleep $delay
npm i -D gulp-load-plugins
echo "-----------"
echo "$((++count)) из $itogo"
echo "del"
sleep $delay
npm i -D del
echo "-----------"
echo "$((++count)) из $itogo"
echo "browser-sync"
sleep $delay
npm i -D browser-sync
echo "-----------"
echo "$((++count)) из $itogo"
echo "imagemin-pngquant"
sleep $delay
npm i -D imagemin-pngquant
echo "-----------"
echo "$((++count)) из $itogo"
echo "stream-combiner2"
sleep $delay
npm i -D stream-combiner2
echo "-----------"
echo "Все gulp модули загружены"
echo "-----------"

echo "Переходим к bower"
echo "Установка bower-модулей в src"
sleep $delay
cd src
echo "-----------"
echo "$((++countBower)) из $itogoBower"
echo "neat"
sleep $delay
bower i -S neat
