#!/bin/bash

echo "Структура"
sleep 2
mkdir tmp
mkdir manifest
mkdir src
mkdir src/scss
mkdir src/img
mkdir src/template
mkdir src/fonts
mkdir dst

cd src/
touch index.html
cd scss/
touch main.scss
cd ../..


let countBower=0
let itogoBower=1

# пределать bower 
echo "-----------"
echo "Сначала bower"
echo "bower init"
sleep 2
bower init
echo "Установка bower модулей в src"
sleep 2
#cd src
echo "-----------"
echo "$((++countBower)) из $itogoBower"
echo "neat"
sleep 2
#bower i -S neat

echo "Переходим к Gulp"
echo "npm init"
sleep 5
npm init 

echo "package.json"
echo "npm install"
npm install


# переделать
echo "git init"
sleep 5
#git init








